"""initial schema

Revision ID: 75893942aef3
Revises:
Create Date: 2026-08-11 05:55:31.777543

Hand-written rather than autogenerated: an initial migration has nothing to
diff against, and most of what matters here (the vector extension, the HNSW
and GIN indexes, RLS enablement and policies, the FK into Supabase's `auth`
schema) is invisible to autogenerate anyway.

Literals are intentionally duplicated from the models instead of imported.
A migration is a snapshot of the schema at one point in time; importing
`EMBEDDING_DIMENSIONS` would silently rewrite history the day it changes.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75893942aef3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


EMBEDDING_DIMENSIONS = 1536

# Owner-scoped read/write for chat data. Wrapped in `select` so Postgres
# evaluates auth.uid() once per statement rather than once per row.
OWNS_THREAD = """
    exists (
        select 1 from public.chat_threads t
        where t.id = chat_messages.thread_id
          and t.user_id = (select auth.uid())
    )
"""

OWNS_CITED_MESSAGE = """
    exists (
        select 1
        from public.chat_messages m
        join public.chat_threads t on t.id = m.thread_id
        where m.id = message_citations.message_id
          and t.user_id = (select auth.uid())
    )
"""


def upgrade() -> None:
    # Supabase keeps extensions out of `public`; the `extensions` schema is on
    # the default search_path for every Supabase role.
    op.execute("create extension if not exists vector with schema extensions")

    # --- users ---------------------------------------------------------

    op.create_table(
        "users",
        # No server default: the id is always the verified Supabase auth id.
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["auth.users.id"],
            name="fk_users_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # --- source_documents ----------------------------------------------

    op.create_table(
        "source_documents",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("accession_number", sa.Text(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("cik", sa.Text(), nullable=False),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_source_documents"),
        sa.UniqueConstraint(
            "accession_number", name="uq_source_documents_accession_number"
        ),
    )
    op.create_index("ix_source_documents_ticker", "source_documents", ["ticker"])
    op.create_index(
        "ix_source_documents_fiscal_year", "source_documents", ["fiscal_year"]
    )

    # --- document_chunks -----------------------------------------------

    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(EMBEDDING_DIMENSIONS),
            nullable=True,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_document_chunks"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name="fk_document_chunks_document_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_document_chunks_document_id_chunk_index",
        ),
    )
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_document_chunks_search_vector",
        "document_chunks",
        ["search_vector"],
        postgresql_using="gin",
    )
    op.create_index(
        "ix_document_chunks_metadata",
        "document_chunks",
        ["metadata"],
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )

    # --- chat_threads ---------------------------------------------------

    op.create_table(
        "chat_threads",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat_threads"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_chat_threads_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_chat_threads_user_id_updated_at",
        "chat_threads",
        ["user_id", sa.text("updated_at DESC")],
    )

    # --- chat_messages --------------------------------------------------

    op.create_table(
        "chat_messages",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="chat_message_role"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chat_messages"),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chat_threads.id"],
            name="fk_chat_messages_thread_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_chat_messages_thread_id_created_at",
        "chat_messages",
        ["thread_id", "created_at"],
    )

    # --- message_citations ----------------------------------------------

    op.create_table(
        "message_citations",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("citation_index", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_message_citations"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_messages.id"],
            name="fk_message_citations_message_id",
            ondelete="CASCADE",
        ),
        # SET NULL, not CASCADE: re-ingesting the corpus replaces chunk rows,
        # and a citation that silently disappeared would break the product's
        # one guarantee. The snapshotted excerpt survives either way.
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name="fk_message_citations_chunk_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
            name="fk_message_citations_document_id",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint(
            "message_id",
            "citation_index",
            name="uq_message_citations_message_id_citation_index",
        ),
    )

    _enable_row_level_security()


def _enable_row_level_security() -> None:
    """Deny-by-default on every table, then grant back narrowly.

    The backend's service-role key bypasses all of this. These policies bound
    what a browser holding a user's anon-key JWT can reach if it ever queries
    Supabase directly.
    """
    for table in (
        "users",
        "source_documents",
        "document_chunks",
        "chat_threads",
        "chat_messages",
        "message_citations",
    ):
        op.execute(f"alter table public.{table} enable row level security")

    op.execute("""
        create policy users_select_own on public.users
        for select to authenticated
        using (id = (select auth.uid()))
    """)
    op.execute("""
        create policy users_update_own on public.users
        for update to authenticated
        using (id = (select auth.uid()))
        with check (id = (select auth.uid()))
    """)

    # The corpus is shared reference data, not per-user data. Any signed-in
    # analyst may read it; nobody may write it except the service role.
    op.execute("""
        create policy source_documents_read on public.source_documents
        for select to authenticated
        using (true)
    """)
    op.execute("""
        create policy document_chunks_read on public.document_chunks
        for select to authenticated
        using (true)
    """)

    op.execute("""
        create policy chat_threads_own on public.chat_threads
        for all to authenticated
        using (user_id = (select auth.uid()))
        with check (user_id = (select auth.uid()))
    """)
    op.execute(f"""
        create policy chat_messages_own on public.chat_messages
        for all to authenticated
        using ({OWNS_THREAD})
        with check ({OWNS_THREAD})
    """)
    op.execute(f"""
        create policy message_citations_own on public.message_citations
        for all to authenticated
        using ({OWNS_CITED_MESSAGE})
        with check ({OWNS_CITED_MESSAGE})
    """)


def downgrade() -> None:
    # Policies and indexes drop with their tables.
    op.drop_table("message_citations")
    op.drop_table("chat_messages")
    op.drop_table("chat_threads")
    op.drop_table("document_chunks")
    op.drop_table("source_documents")
    op.drop_table("users")

    sa.Enum(name="chat_message_role").drop(op.get_bind(), checkfirst=True)

    # The `vector` extension is deliberately left installed — it is a
    # project-level facility and something else may depend on it.
