"""`document_chunks` — retrieval-ready passages of a filing."""

import uuid
from datetime import datetime
from typing import Any, Final

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Computed,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.database.models.base import Base, created_at_column

# Deliberately a constant rather than `settings.openai_embedding_dimensions`:
# the column width is baked into a migration, so it must not drift with the
# environment. Changing it requires a migration that rebuilds the HNSW index.
EMBEDDING_DIMENSIONS: Final[int] = 1536

# Fixed regconfig — a generated column's expression must be IMMUTABLE, which
# rules out the one-argument `to_tsvector(text)` that reads a GUC.
SEARCH_VECTOR_EXPRESSION: Final[str] = "to_tsvector('english', content)"


class DocumentChunk(Base):
    """A retrieval-ready passage of a filing.

    Both halves of hybrid retrieval read this table: `embedding` for the
    pgvector semantic query and `search_vector` for the full-text query.
    """

    __tablename__ = "document_chunks"
    __table_args__ = (
        # Also serves as the index for neighbor lookups
        # (`read_surrounding_chunks` scans by document_id + chunk_index range).
        UniqueConstraint("document_id", "chunk_index"),
        # Semantic half of hybrid retrieval. `vector_cosine_ops` because
        # OpenAI embeddings are L2-normalized and queries use `<=>`; an index
        # built for a different operator class simply will not be used.
        Index(
            "ix_document_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # Lexical half of hybrid retrieval.
        Index(
            "ix_document_chunks_search_vector",
            "search_vector",
            postgresql_using="gin",
        ),
        # Metadata filters (ticker, fiscal year, form type) applied before
        # ranking. `jsonb_path_ops` is smaller and faster than the default for
        # containment queries, which is all we do.
        Index(
            "ix_document_chunks_metadata",
            "metadata",
            postgresql_using="gin",
            postgresql_ops={"metadata": "jsonb_path_ops"},
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, server_default=text("gen_random_uuid()")
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("source_documents.id", ondelete="CASCADE")
    )

    chunk_index: Mapped[int] = mapped_column(Integer)
    content: Mapped[str] = mapped_column(Text)
    token_count: Mapped[int] = mapped_column(Integer)

    page: Mapped[int | None] = mapped_column(Integer)
    section: Mapped[str | None] = mapped_column(Text)

    # Nullable: chunks are written first, then embedded in batches. A NULL
    # embedding means "ingested but not yet embedded".
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIMENSIONS))

    # Generated by Postgres, never written by the app.
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR, Computed(SEARCH_VECTOR_EXPRESSION, persisted=True)
    )

    # Filing metadata copied down from `source_documents` (ticker, company,
    # filing type, filing date, year, accession number, source offsets) so
    # retrieval can filter and cite without a join on every candidate row.
    chunk_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, server_default=text("'{}'::jsonb")
    )

    created_at: Mapped[datetime] = created_at_column()
